<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Kue Balok Choco Original',
                'slug' => Str::slug('kue-balok-choco-original'),
                'category_id' => 1,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 22000,
                'image' => null,
                'is_active' => true,
                'featured' => true,
            ],
            [
                'name' => 'Kue Balok Choco Banana',
                'slug' => Str::slug('kue-balok-choco-banana'),
                'category_id' => 1,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 22000,
                'image' => null,
                'is_active' => true,
                'featured' => true,
            ],
            [
                'name' => 'Bakpia Butter Coklat',
                'slug' => Str::slug('bakpia-butter-coklat'),
                'category_id' => 1,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 16000,
                'image' => null,
                'is_active' => true,
                'featured' => true,
            ],
            [
                'name' => 'Bakpia Butter Keju',
                'slug' => Str::slug('bakpia-butter-keju'),
                'category_id' => 1,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 16000,
                'image' => null,
                'is_active' => true,
                'featured' => true,
            ],
            [
                'name' => 'Bakpia Butter Kacang Ijo',
                'slug' => Str::slug('bakpia-butter-kacang-ijo'),
                'category_id' => 1,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 16000,
                'image' => null,
                'is_active' => true,
                'featured' => true,
            ],
            [
                'name' => 'Bolen Pisang Cokelat Lumer',
                'slug' => Str::slug('bolen-pisang-cokelat-lumer'),
                'category_id' => 1,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 22000,
                'image' => null,
                'is_active' => true,
                'featured' => true,
            ],
            [
                'name' => 'Basreng Pedas Daun Jeruk',
                'slug' => Str::slug('basreng-pedas-daun-jeruk'),
                'category_id' => 2,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 15000,
                'image' => null,
                'is_active' => true,
                'featured' => true,
            ],
            [
                'name' => 'Basreng Original Daun Jeruk',
                'slug' => Str::slug('basreng-original-daun-jeruk'),
                'category_id' => 2,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 15000,
                'image' => null,
                'is_active' => true,
                'featured' => false,
            ],
            [
                'name' => 'Keripik Pisang Lumer',
                'slug' => Str::slug('keripik-pisang-lumer'),
                'category_id' => 2,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 16000,
                'image' => null,
                'is_active' => true,
                'featured' => false,
            ],
            [
                'name' => 'Keripik Singkong Lumer',
                'slug' => Str::slug('keripik-singkong-lumer'),
                'category_id' => 2,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 16000,
                'image' => null,
                'is_active' => true,
                'featured' => false,
            ],
            [
                'name' => 'Soes Kering Lumer',
                'slug' => Str::slug('soes-kering-lumer'),
                'category_id' => 2,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 16000,
                'image' => null,
                'is_active' => true,
                'featured' => false,
            ],
            [
                'name' => 'Es Coklat Lumerr',
                'slug' => Str::slug('es-coklat-lumerr'),
                'category_id' => 3,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 16000,
                'image' => null,
                'is_active' => true,
                'featured' => false,
            ],
            [
                'name' => 'Mie Lidi Si Umang',
                'slug' => Str::slug('mie-lidi-si-umang'),
                'category_id' => 4,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 15000,
                'image' => null,
                'is_active' => true,
                'featured' => false,
            ],
            [
                'name' => 'Batagor Spicy Si Kaya',
                'slug' => Str::slug('batagor-spicy-si-kaya'),
                'category_id' => 4,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 18000,
                'image' => null,
                'is_active' => true,
                'featured' => false,
            ],
            [
                'name' => 'Batagor Original Si Kaya',
                'slug' => Str::slug('batagor-original-si-kaya'),
                'category_id' => 4,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 18000,
                'image' => null,
                'is_active' => true,
                'featured' => false,
            ],
            [
                'name' => 'Basreng Si Kaya',
                'slug' => Str::slug('basreng-si-kaya'),
                'category_id' => 4,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 22000,
                'image' => null,
                'is_active' => true,
                'featured' => false,
            ],
            [
                'name' => 'Basreng Ngemil Yuk',
                'slug' => Str::slug('basreng-ngemil-yuk'),
                'category_id' => 4,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 22000,
                'image' => null,
                'is_active' => true,
                'featured' => false,
            ],
            [
                'name' => 'Keripuk Seblak Ngemil Yuk',
                'slug' => Str::slug('keripuk-seblak-ngemil-yuk'),
                'category_id' => 4,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 22000,
                'image' => null,
                'is_active' => true,
                'featured' => false,
            ],
            [
                'name' => 'Makaroni Cikruh Ngemil Yuk',
                'slug' => Str::slug('makaroni-cikruh-ngemil-yuk'),
                'category_id' => 4,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 22000,
                'image' => null,
                'is_active' => true,
                'featured' => false,
            ],
            [
                'name' => 'Siomay Mini Pangsit Ngemil Yuk',
                'slug' => Str::slug('siomay-mini-pangsit-ngemil-yuk'),
                'category_id' => 4,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 22000,
                'image' => null,
                'is_active' => true,
                'featured' => false,
            ],
            [
                'name' => 'Brownies Kering Almond',
                'slug' => Str::slug('brownies-kering-almond'),
                'category_id' => 4,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 15000,
                'image' => null,
                'is_active' => true,
                'featured' => false,
            ],
            [
                'name' => 'Brownies Kering Chococip',
                'slug' => Str::slug('brownies-kering-chococip'),
                'category_id' => 4,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 15000,
                'image' => null,
                'is_active' => true,
                'featured' => false,
            ],
            [
                'name' => 'Brownies Kering Keju',
                'slug' => Str::slug('brownies-kering-keju'),
                'category_id' => 4,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 15000,
                'image' => null,
                'is_active' => true,
                'featured' => false,
            ],
            [
                'name' => 'Brownies Kering Kismis',
                'slug' => Str::slug('brownies-kering-kismis'),
                'category_id' => 4,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 15000,
                'image' => null,
                'is_active' => true,
                'featured' => false,
            ],
            [
                'name' => 'Soes Milo Gobanco',
                'slug' => Str::slug('soes-milo-gobanco'),
                'category_id' => 4,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 18000,
                'image' => null,
                'is_active' => true,
                'featured' => false,
            ],
            [
                'name' => 'Chips Milo Gobanco',
                'slug' => Str::slug('chips-milo-gobanco'),
                'category_id' => 4,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 18000,
                'image' => null,
                'is_active' => true,
                'featured' => false,
            ],
            [
                'name' => 'Ring Milu Gobanco',
                'slug' => Str::slug('ring-milu-gobanco'),
                'category_id' => 4,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 18000,
                'image' => null,
                'is_active' => true,
                'featured' => false,
            ],
            [
                'name' => 'Lopta Ball Gobanco',
                'slug' => Str::slug('lopta-ball-gobanco'),
                'category_id' => 4,
                'description' => 'Ini adalah contoh produk yang tidak aktif.',
                'price' => 18000,
                'image' => null,
                'is_active' => true,
                'featured' => false,
            ],
        ];
        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
